name: example
description: Example app showing how to use the math_keyboard_plus package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  math_keyboard_plus:
    path: ../

flutter:
  uses-material-design: true
